export const TAG_SUG = [
	"ASCII", "ActiveDirectory", "Adwords", "Artificial Intelligence (AI)", 
	"Algorithms", "Android", "Android Studio", "API", "Apache", 
	"AWS", "Automation", "Automated Testing", 
	"Bandwidth", "Bash", "BitTorrent",  
	"Big Data", "Binary Search", "BIOS", "Bloatware", 
	"Cache", "Captcha", "Cassendra", "CodeIgniter", "Chef", 
	"Cloud Computing", 
	"Compiling Statistics", 
	"Common Gateway Interface (CGI)", 
	"Content Management Systems (CMS)", 
	"CPU", 
	"Cybersecurity", 
	"Data Analytics",
	"Data Analytics", "Data Centre", "Data Warehouse", 
	"Dashboard",  
	"Data Mining", 
	"Data Shard", 
	"Data Structure", 
	"Database", 
	"Database Design", 
	"Database Management", 
	"Deep Learning", 
	"Desktop as a Service (DaaS)", 
	"Documentation", 
	"Domain Name System (DNS)", 
	"Debugging",
	"Design",
	"Development", 
	"Disaster Recovery", "Disaster Recovery Planning", 
	"Disaster Recovery as a Service (DRaaS)", 
	"Digital Subscriber Line (DSL)", 
	"Docker", 
	"Email", 
	"Encryption", 
	"Enterprise Resource Planning (ERP)", 
	"Express.js", 
	"File Transfer Protocol (FTP)", "Firewall", 
	"Fragmentation", 
	"Game Development", 
	"Git", 
	"Graphical user interface (GUI)", 
	"Hadoop", 
	"Hardware",
	"HTML", 
	"Human-Computer Interaction (HCI)", 
	"HyperText Transfer Protocol (HTTP)", 
	"Information Security",   
	"Infrastructure", "Infrastruture as Code (IaC)", 
	"IaaS", "IOS", "IntelliJ Enterprise", 
	"IntelliJ Community", 
	"Internet Service Provider (ISP)",   
	"JAR", "J2EE", "JaCoCo", "Java Servlet", "JDK", "Jenkins", "Jira", 
	"JSON", 
	"Jupiter Notebook", "Kernel", "Kerning", "Kubernete", 
	"Latin", "Linux", "Local Area Network (LAN)",  
	"Mac OS", "Macintosh", 
	"MapReduce", "MatLab", "Media Access Control (MAC)", 
	"Network as a Service (NaaS)", 
	"Networking", "Network Adapter", "Network Architecture", 
	"Network Security", "Microsoft Office 365", 
	"Messaging Application Programming Interface (MAPI)", 
	"Mobile Development", "Mobile", 
	"Modeling", "Modem", "Modification", "MongoDB", 
	"Multi-factor authentication (MAF)", 
	"Multipurpose Internet Mail Extensions (MIME)", 
	"Node.js", "OAuth", 
	"PaaS", "Pig", "PowerShell", "Puppet", 
	"Public Key Encryption",  
	"React.js", "Quantitative Research", 
	"Quantitative Reports", "SaaS", "SaSS", 
	"SalesForce", "SDK", "Servers", 
	"Server Encryption", "Search Engine Optimization (SEO)", 
	"Shopify", "Software", 
	"SonarQube", "SonarLint", "Spark", 
	"Spring", "Sprint Boot", "Statistical Analysis", "Storage", 
	"MySQL", "SQLite", "SQL Developer", "SQL Plus", "TCP/IP", 
	"Testng", "Tag Image File Format (TIFF)", 
	"Tools", "Troubleshooting", 
	"Wide Area Network (WAN)", 
	"Wireless Application Protocol (WAP)", 
	"Web Analytics", "Windows", 
	"Wireless Local Area Network (WLAN)", "Wordpress",  
	"Visual Studio", "Visual Studio Code", "Visualisation", 
	"Virtualisation",  
	"2PL", "Ubuntu", "Uniform Resource Locator (URL)", 
	"Unity3D", "Unity2D", "Unix"  
]